name: Deploy Web
on:
  push: 
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPNAME}}
          heroku_email: ${{secrets.HEROKU_USER}}
          justlogin: true
      - run: |
          docker build -t registry.heroku.com/craftathome/web -f CraftAtHome/Dockerfile .
          docker push registry.heroku.com/craftathome/web
          heroku container:release web --app craftathome
          exit 0
          
